### ISSUE TITLE
Data missingness in pol.zip

### ISSUE THREAD

**Issue by kylebgorman** [unimorph/pol#2]
The data from the online gramamtical dictionary stored in `pol.zip` is riddled with incomplete paradigms. I just took a look at nouns. Here are some summary statistics. Out of 273,843 lexemes:

* 39,402 nouns are missing at least one of the 14 forms in the paradigm
* 20,099 masculine inanimate nouns are missing a form; only **3** masculine inanimates have a complete paradigm.
* Of these masculine inanimates, 20,034 are missing the nominative singular, which can be trivially imputed (it's the same as the lemma, of course)
* But 2,379 are missing other forms too

@wkieras

**Comment by wkieras** [comment]
This is really unfortunate bug, thanks for reporting. I've corrected the data and uploaded to the repo. I've checked nouns and adjective for paradigm completeness (they should contain all the forms now with exception of PT nouns and defective lexemes) and will try to run some tests for verbs in the coming days.

**Comment by kylebgorman** [comment]
I'll inspect locally and can close if things are looking good.

**Comment by kylebgorman** [comment]
Looks like I'm getting way more masculine inanimate complete paradigms, which we love to see. Thanks for the quick turn-around: I take it was an error in whatever code you're using to generate the data from the online dictionary? Closing now.

**Comment by wkieras** [comment]
Yes, I had a bug in an export templates from the dictionary's database.
